ecomprj/core/urls.py
from django.urls import path, include
from core.views import (index, product_list_view, product_detail_view,
                        category_list_view, category_product_list_view,
                        vendor_list_view, vendor_detail_view, tag_list,
                        ajax_add_review, search_view, filter_product,
                        add_to_cart, cart_view, delete_item_from_cart,
                        update_cart, checkout, payment_completed_view,
                        payment_failed, customer_dashboard, order_detail,
                        make_address_default, wishlist_view, add_to_wishlist,
                        remove_wishlist, contact, ajax_contact_form, about_us,
                        purchase_guide, privacy_policy, terms_of_service,
                        save_checkout_info, create_checkout_session)
app_name = "core"

urlpatterns = [
    # homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>", product_detail_view, name="product-detail"),

    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>", category_product_list_view, name="category-product-list"),

    # Vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>", vendor_detail_view, name="vendor-detail"),

    # Tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add review
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),

    # Filter product URL
    path("filter-products/", filter_product, name="filter-product"),

    # Add to cart URL
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    # Cart page URL
    path("cart/", cart_view, name="cart"),

    # Delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update cart -- this urlpath must be the same as in the function.js
    path("update-cart/", update_cart, name="update-cart"),

    # Checkout URL
    path("checkout/<oid>", checkout, name="checkout"),

    # PayPal URL
    path("paypal/", include('paypal.standard.ipn.urls')),

    # Payment successful
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),

    # Payment failed
    path("payment-failed/", payment_failed, name="payment-failed"),

    # Dashboard URL
    path("dashboard/", customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    # Making Address Default
    path("make-default-address/", make_address_default, name="make-default-address"),

    # Wishlist Page
    path("wishlist/", wishlist_view, name="wishlist"),

    # Added to Wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wistlist"),

    # Removing from Wishlist
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wistlist"),

    # Contact us
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),

    path("about-us/", about_us, name="about-us"),
    path("purchase-guide/", purchase_guide, name="purchase-guide"),
    path("privacy-policy/", privacy_policy, name="privacy-policy"),
    path("terms-of-service/", terms_of_service, name="terms-of-service"),

    # New Routes
    path("save_checkout_info", save_checkout_info, name="save_checkout_info"),
    path("api/create_checkout_session/<oid>/", create_checkout_session,
         name="api_checkout_session"),
]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/useradmin/urls.py
from django.urls import path
from useradmin.views import (dashboard, products, add_product,
                             edit_product, delete_product, orders,
                             order_detail, change_order_status,
                             shop_page, reviews, settings, change_password)

app_name = "useradmin"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("products/", products, name="products"),
    path("add-product/", add_product, name="add-product"),
    path("edit-product/<pid>/", edit_product, name="edit-product"),
    path("delete-product/<pid>/", delete_product, name="delete-product"),
    path("orders/", orders, name="orders"),
    path("order-detail/<id>/", order_detail, name="order-detail"),
    path("change-order-status/<oid>/", change_order_status, name="change-order-status"),
    path("shop-page/", shop_page, name="shop-page"),
    path("reviews/", reviews, name="reviews"),
    path("settings/", settings, name="settings"),
    path("change-password/", change_password, name="change-password"),
]

ecomprj/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path("profile/update/", views.profile_update, name="profile-update"),
]

ecomprj/core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User
from taggit.managers import TaggableManager
from django_ckeditor_5.fields import CKEditor5Field

STATUS_CHOICE = (
    ("processing", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)

RATING = (
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="cat", alphabet="abcdefgh12345")
    title = models.CharField(max_length=100, default="Food")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Tags(models.Model):
    pass


class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length=10, max_length=20,
                         prefix="ven", alphabet="abcdefgh12345")

    title = models.CharField(max_length=100, default="Nestify")
    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    cover_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    # description = models.TextField(null=True, blank=True, default="I am an Amazing Vendor")
    description = CKEditor5Field(null=True, blank=True, default="I am an Amazing Vendor",
                                 config_name="extends")

    address = models.CharField(max_length=100, default="123 Main Street")
    contact = models.CharField(max_length=100, default="+123 (456) 789")
    chat_resp_time = models.CharField(max_length=100, default="100")
    shipping_on_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")
    days_return = models.CharField(max_length=100, default="100")
    warranty_period = models.CharField(max_length=100, default="100")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Vendors"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title


class Product(models.Model):
    pid = ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefgh12345")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                 null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="vendor")

    title = models.CharField(max_length=100, default="Fresh Pear")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    # description = models.TextField(null=True, blank=True, default="This is the product")
    description = CKEditor5Field(null=True, blank=True, default="This is the product",
                                 config_name="extends")

    price = models.DecimalField(max_digits=12, decimal_places=2, default="1.99")
    old_price = models.DecimalField(max_digits=12, decimal_places=2, default="2.99")

    # specifications = models.TextField(null=True, blank=True)
    specifications = CKEditor5Field(null=True, blank=True, config_name="extends")
    type = models.CharField(max_length=100, default="Organic", null=True, blank=True)
    stock_count = models.CharField(max_length=100, default="10", null=True, blank=True)
    life = models.CharField(max_length=100, default="100 Days", null=True, blank=True)
    mfd = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    tags = TaggableManager(blank=True)

    # tags = models.ForeignKey(Category, related_name='tags', on_delete=models.SET_NULL, null=True)

    product_status = models.CharField(choices=STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=True)
    digital = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="1234567890")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

    def get_percentage(self):
        new_price = 100 - (self.price / self.old_price) * 100
        return new_price


class ProductImages(models.Model):
    images = models.ImageField(upload_to="product_images", default="product.jpg")
    product = models.ForeignKey(Product, related_name="p_images",
                                on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products Images"


# Cart, Order, OrderItems and Address
class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)

    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)

    price = models.DecimalField(max_digits=12, decimal_places=2, default="0.00")
    saved = models.DecimalField(max_digits=12, decimal_places=2, default="0.00")
    coupons = models.ManyToManyField("core.Coupon", blank=True)
    shipping_method = models.CharField(max_length=100, null=True, blank=True)
    tracking_id = models.CharField(max_length=100, null=True, blank=True)
    tracking_website_address = models.CharField(max_length=100, null=True, blank=True)

    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing",
                                      null=True, blank=True)
    sku = ShortUUIDField(null=True, blank=True, length=5, prefix="SKU",
                         max_length=20, alphabet="1234567890")
    oid = ShortUUIDField(null=True, blank=True, length=5, max_length=20, alphabet="1234567890")

    stripe_payment_intent = models.CharField(max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Cart Order"


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200, default=0)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=12, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=12, decimal_places=2, default="1.99")

    class Meta:
        verbose_name_plural = "Cart Order Items"

    def order_img(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image))


# Product Review, wishlists, Address
class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,
                                null=True, related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"

    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.rating


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Wishlists"

    def __str__(self):
        return self.product.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    mobile = models.CharField(max_length=300, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Adresses"


class Coupon(models.Model):
    code = models.CharField(max_length=50)
    discount = models.IntegerField(default=1)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

ecomprj/useradmin/forms.py
from core.models import Product
from django import forms


class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
                            attrs={"placeholder": "Enter product title", "class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(
                                  attrs={"placeholder": "Product Description",
                                         "class": "form-control"}))
    price = forms.CharField(widget=forms.NumberInput(
                            attrs={"placeholder": "Sale Price", "class": "form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(
                                attrs={"placeholder": "Old Price", "class": "form-control"}))
    type = forms.CharField(widget=forms.TextInput(
                           attrs={"placeholder": "Type of product e.g. organic cream",
                                  "class": "form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(
                                  attrs={"placeholder": "How many are in stock?",
                                         "class": "form-control"}))
    life = forms.CharField(widget=forms.TextInput(
                           attrs={"placeholder": "How long would this product live?",
                                  "class": "form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(
                              attrs={"placeholder": "e.g. 22-11-2024",
                                     "class": "form-control"}))
    tags = forms.CharField(widget=forms.TextInput(
                           attrs={"placeholder": "Tags", "class": "form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class": "form-control"}))

    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'specifications',
            'type',
            'stock_count',
            'life',
            'mfd',
            'tags',
            'digital',
            'category',
        ]

ecomprj/templates/useradmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>E-commerce Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="assets2/imgs/theme/favicon.svg" />
        <!-- Template CSS -->
        <link href="{% static 'assets2/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

    </head>

    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="/useradmin/" class="brand-wrap">
                    <img src="https://clipground.com/images/ecommerce-logo-png-11.png" class="logo" alt="E-commerce Dashboard" />
                </a>
                <div>
                    <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
                </div>
            </div>
            <nav>
                <ul class="menu-aside">
                    <li class="menu-item {% if '/useradmin/dashboard/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:dashboard' %}">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/products/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:products' %}">
                            <i class="icon material-icons md-shopping_bag"></i>

                            <span class="text">Products</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/orders/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:orders' %}">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:shop-page' %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Shop Page</span>
                        </a>
                    </li>
                    <li class="menu-item ">
                        <a class="menu-link" href="{% url 'useradmin:add-product' %}">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Add product</span>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:reviews' %}">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                    </li>
                </ul>
                <hr />
                <ul class="menu-aside">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:settings' %}">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Settings</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:change-password' %}">
                            <i class="icon material-icons md-lock"></i>
                            <span class="text"> Change Password </span>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'userauths:sign-out' %}">
                            <i class="icon material-icons md-arrow_forward"></i>
                            <span class="text">Logout</span>
                        </a>
                    </li>
                </ul>
                <br />
                <br />
            </nav>
        </aside>
        <main class="main-wrap">
            <header class="main-header navbar">
                <div class="col-search">
                    
                </div>
                <div class="col-nav">
                    <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                    <ul class="nav">
                       
                        <li class="nav-item">
                            <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                        </li>
                        
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> 
                                
                                {% if request.user.profile.image %}
                                <img class="img-xs rounded-circle" src="{{request.user.profile.image.url}}" alt="User" />
                                {% else %}
                                <img class="img-xs rounded-circle" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User" />

                                {% endif %}
                                    
                            </a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                                <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </header>

            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 3000)
                </script>

            {% block content %} 
            
            {% endblock content %}

            <!-- content-main end// -->
            <footer class="main-footer font-xs">
                <div class="row pb-30 pt-15">
                    <div class="col-sm-6">
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        &copy; E-commerce - HTML Ecommerce Template .
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">All rights reserved</div>
                    </div>
                </div>
            </footer>
        </main>
        <script src="{% static 'assets2/js/vendors/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/select2.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/perfect-scrollbar.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/jquery.fullscreen.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/chart.js' %}"></script>
        <!-- Main Script -->
        <script src="{% static 'assets2/js/main.js?v=1.1' %}" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <!-- <script src="{% static 'assets2/js/custom-chart.js' %}" type="text/javascript"></script> -->
    </body>
</html>

ecomprj/templates/useradmin/products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% block content %}

<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Products List</h2>
            <p>Manage all your products from here</p>
        </div>
        <div>
            <a href="{% url 'useradmin:add-product' %}" class="btn btn-primary btn-sm rounded">Create Product</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row align-items-center">
                <div class="col-md-2 col-6">
                    <select class="form-select">
                        <option selected>Status</option>
                        <option>Active</option>
                        <option>Disabled</option>
                        <option>Show all</option>
                    </select>
                </div>
            </div>
        </header>
        <div class="card-body">
            {% for p in all_products %}
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="">
                            <div class="left">
                                <img src="{{ p.image.url }}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 15px" class="img-sm img-thumbnail" alt="Item" />
                            </div>
                            <div class="info">
                                <h6 class="mb-0">{{ p.title }}</h6>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{ p.price }}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-status">
                        <span class="badge alert-dark">{{ p.status }}</span>
                    </div>
                    <div class="col-lg-1 col-sm-2 col-4 col-date">
                        <span>{{ p.date|date:"d M, Y" }}</span>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'useradmin:edit-product' p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                        <a href="{% url 'useradmin:delete-product' p.pid %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
    <div class="pagination-area mt-30 mb-50">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-start">
                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                <li class="page-item"><a class="page-link" href="#">02</a></li>
                <li class="page-item"><a class="page-link" href="#">03</a></li>
                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="#">16</a></li>
                <li class="page-item">
                    <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                </li>
            </ul>
        </nav>
    </div>
</section>

{% endblock content %}